version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ../../:/app
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_BASE_URL=http://api:5000/v1

  psql:
    image: postgres:latest
    container_name: psql
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dev
    volumes:
      - masterbom-db:/var/lib/postgresql/data

  api:
    container_name: api
    image: ghcr.io/masterbomb/api:master
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PGHOST: psql
      PGUSER: admin
      PGDATABASE: dev
      PGPORT: 5432
    depends_on:
      - psql

volumes:
  masterbom-db:
