version: '3.9'

services:
  postgresql:
    container_name: postgres
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    image: postgres:latest
    volumes:
      - masterbom-db:/var/lib/postgresql/data
  masterbom:
    container_name: nodejs
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment: 
      NODE_ENV: ${NODE_ENV}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgresql

volumes:
  masterbom-db: