version: '3.9'

services:
  postgresql:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${PGPORT}:${PGPORT}"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      PGHOST: ${PGHOST}
    volumes:
      - masterbom-db:/var/lib/postgresql/data
      - "./psql/initdb.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - db
  masterbom:
    container_name: masterbom
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    env_file: 
      - .env
    build:
      context: ../
      dockerfile: docker/node/Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    depends_on:
      - postgresql
    networks:
      - db

volumes:
  masterbom-db:

networks:
  db:
    driver: bridge
